;–start job file –

[global]
#runtime=300
#size=256G
#nrfiles=1
#directory=/data

[fio-seqread-path-latency]
name=fio-seqread-path-latency
group_reporting=1
ioengine=psync
iodepth=1
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=read
bs=4K
direct=1
fsync=0
fdatasync=0
thread=1
numjobs=1
time_based=1
ramp_time=3
lockmem=128m

[fio-seqwrite-path-latency]
name=fio-seqwrite-path-latency
group_reporting=1
ioengine=psync
iodepth=1
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=write
bs=4K
direct=1
fsync=0
fdatasync=0
thread=1
numjobs=1
time_based=1
ramp_time=3
lockmem=128m

[fio-randread-latency]
name=fio-randread-latency
group_reporting=1
ioengine=psync
iodepth=1
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=randread
bs=4K
direct=1
fsync=0
fdatasync=0
thread=1
numjobs=1
time_based=1
ramp_time=3
lockmem=128m

[fio-randwrite-latency]
name=fio-randwrite-latency
group_reporting=1
ioengine=psync
iodepth=1
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=randwrite
bs=4K
direct=1
fsync=0
fdatasync=0
thread=1
numjobs=1
time_based=1
ramp_time=3
lockmem=128m

[global]
#runtime=600
#size=256G
#nrfiles=1
#directory=/data
group_reporting=1
ioengine=libaio
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=read
direct=1
fsync=0
fdatasync=0
thread=1
time_based=1
ramp_time=3
lockmem=128m

[fio-seqread-throughput-256-32-1]
name=fio-seqread-throughput-256-32-1
bs=256K
iodepth=32
numjobs=1

[fio-seqread-throughput-512-32-1]
name=fio-seqread-throughput-512-32-1
bs=512K
iodepth=32
numjobs=1

[fio-seqread-throughput-2048-32-1]
name=fio-seqread-throughput-2048-32-1
bs=2048K
iodepth=32
numjobs=1


[global]
#runtime=600
#size=256G
#nrfiles=1
#directory=/data
group_reporting=1
ioengine=libaio
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=write
direct=1
fsync=0
fdatasync=0
thread=1
time_based=1
ramp_time=3
lockmem=128m

[fio-seqwrite-throughput-256-32-1]
name=fio-seqwrite-throughput-256-32-1
bs=256K
iodepth=32
numjobs=1

[fio-seqwrite-throughput-512-32-1]
name=fio-seqwrite-throughput-512-32-1
bs=512K
iodepth=32
numjobs=1

[fio-seqwrite-throughput-2048-32-1]
name=fio-seqwrite-throughput-2048-32-1
bs=2048K
iodepth=32
numjobs=1


[global]
#runtime=600
#size=256G
#nrfiles=1
#directory=/data
group_reporting=1
ioengine=libaio
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=randread
bs=4K
direct=1
fsync=0
fdatasync=0
thread=1
time_based=1
ramp_time=3

[fio-randread-iops-4-1]
name=fio-randread-IOPS-4-1
iodepth=4
numjobs=1

[fio-randread-iops-8-1]
name=fio-randread-IOPS-8-1
iodepth=8
numjobs=1

[fio-randread-iops-16-1]
name=fio-randread-IOPS-16-1
iodepth=16
numjobs=1

[fio-randread-iops-32-1]
name=fio-randread-IOPS-32-1
iodepth=32
numjobs=1

[fio-randread-iops-64-1]
name=fio-randread-IOPS-64-1
iodepth=64
numjobs=1

[fio-randread-iops-128-1]
name=fio-randread-IOPS-128-1
iodepth=128
numjobs=1

[fio-randread-iops-256-1]
name=fio-randread-IOPS-256-1
iodepth=256
numjobs=1


[global]
#runtime=600
#size=256G
#nrfiles=1
#directory=/data
group_reporting=1
ioengine=libaio
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=randwrite
bs=4K
direct=1
fsync=0
fdatasync=0
thread=1
time_based=1
ramp_time=3
lockmem=128m

[fio-randwrite-iops-4-1]
name=fio-randwrite-IOPS-4-1
iodepth=4
numjobs=1

[fio-randwrite-iops-8-1]
name=fio-randwrite-IOPS-8-1
iodepth=8
numjobs=1

[fio-randwrite-iops-16-1]
name=fio-randwrite-IOPS-16-1
iodepth=16
numjobs=1

[fio-randwrite-iops-32-1]
name=fio-randwrite-IOPS-32-1
iodepth=32
numjobs=1

[fio-randwrite-iops-64-1]
name=fio-randwrite-IOPS-64-1
iodepth=64
numjobs=1

[fio-randwrite-iops-128-1]
name=fio-randwrite-IOPS-128-1
iodepth=128
numjobs=1

[fio-randwrite-iops-256-1]
name=fio-randwrite-IOPS-256-1
iodepth=256
numjobs=1

[global]
#runtime=600
#size=256G
#nrfiles=1
#directory=/data
group_reporting=1
ioengine=libaio
iodepth_low=1
iodepth_batch_submit=1
iodepth_batch_complete_min=1
iodepth_batch_complete_max=1
rw=randrw
percentage_random=100,0
bs=4K
direct=1
fsync=0
fdatasync=0
thread=1
time_based=1
ramp_time=3
lockmem=128m

[fio-randread-write-iops-4-1]
name=fio-randread-write-IOPS-4-1
iodepth=4
numjobs=1

[fio-randread-write-iops-8-1]
name=fio-randread-write-IOPS-8-1
iodepth=8
numjobs=1

[fio-randread-write-iops-16-1]
name=fio-randread-write-IOPS-16-1
iodepth=16
numjobs=1

[fio-randread-write-iops-32-1]
name=fio-randread-write-IOPS-32-1
iodepth=32
numjobs=1

[fio-randread-write-iops-64-1]
name=fio-randread-write-IOPS-64-1
iodepth=64
numjobs=1

[fio-randread-write-iops-128-1]
name=fio-randread-write-IOPS-128-1
iodepth=128
numjobs=1

[fio-randread-write-iops-256-1]
name=fio-randread-write-IOPS-256-1
iodepth=256
numjobs=1

[global]
#runtime=600
size=10G
#nrfiles=1
#directory=/data
group_reporting=1
thread=1
ioengine=psync
bs=32k
direct=0
fsync=0
fdatasync=1
time_based=1

[tidb-randread]
name=tidb-randread-test
rw=randread
iodepth=4
numjobs=4
filename=tidb-randread

[tidb-randread-write]
name=tidb-randread-write-test
rw=randrw
percentage_random=100,0
iodepth=4
numjobs=4
filename=tidb-randread-write

[tidb-randread-write-latency]
name=tidb-randread-write-latency-test
rw=randrw
percentage_random=100,0
iodepth=1
numjobs=1
filename=tidb-randread-write-latency

;–end job file–
